### ISSUE TITLE
Broken `AJAXError` import from maplibre-gl in v2.4.0

### ISSUE THREAD

**Issue by kyoshino** [maptiler/maptiler-sdk-js#127]
I’m afraid that SDK [v2.4.0](https://github.com/maptiler/maptiler-sdk-js/releases/tag/v2.4.0) has introduced the same problem as #99. When I run my client’s SvelteKit project, I get:

```
file:///Users/Kohei/Sites/PROJECT/node_modules/.pnpm/@maptiler+sdk@2.4.0/node_modules/@maptiler/sdk/dist/maptiler-sdk.mjs:8
import x, { AJAXError as Ca } from "maplibre-gl";
            ^^^^^^^^^
SyntaxError: Named export 'AJAXError' not found. The requested module 'maplibre-gl' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'maplibre-gl';
const { AJAXError: Ca } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:146:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:229:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async nodeImport (file:///Users/Kohei/Sites/PROJECT/node_modules/.pnpm/vite@5.4.9_@types+node@22.7.6_sass@1.77.8/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:53045:15)
    at async ssrImport (file:///Users/Kohei/Sites/PROJECT/node_modules/.pnpm/vite@5.4.9_@types+node@22.7.6_sass@1.77.8/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:52903:16)
    at async eval (/Users/Kohei/Sites/PROJECT/src/lib/components/map.svelte:4:31)
    at async instantiateModule (file:///Users/Kohei/Sites/PROJECT/node_modules/.pnpm/vite@5.4.9_@types+node@22.7.6_sass@1.77.8/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:52961:5)
```

Downgrading to v2.3.0 solves the issue. I guess it’s a regression from #124.

**Comment by jonathanlurie** [comment]
Hello @kyoshino thanks for the feedback. I'm out of town for about a week with no access to a computer so i cannot fully test. In the meantime, can you check this option https://github.com/maptiler/maptiler-sdk-js?tab=readme-ov-file#typescript
Let me know how it goes.

**Comment by jonathanlurie** [comment]
@kyoshino could you share a  minimalistic configuration of your sveltkit project so that i can reproduce the issue? Or maybe some svelte cli command to get a setup equivalent to yours?
